package example;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }
    
    public  boolean isVaild(List<String> input) {	    
	    if(input.size() != 4) {
	    	return false;
	    }else {
	    	boolean isRepeat = input.size() != new HashSet<String>(input).size();
	    	return isRepeat;
	    } 	
    }
    // answer 1234
    //input 1357
    public int countB(List<String> answer,List<String> input) {
    	int countB = 0;
    	
    	for(String ans :answer) {
    		for(String ipt : input) {
    			if(ans.equals(ipt)) {
    				countB++;
    			}
    		}
    	}
    	return countB;
    }
    
    public int countA(List<String> answer,List<String> input) {
    	int countA = 0;
    	for(int i = 0;i<answer.size();i++ ) {
    		if(answer.get(i).equals(input.get(i))) {
    			countA++;
    		}
    	}
    	return countA;
    }
    
    public String result(int countA, int countB) {
    	if(countA ==4) {
    		return "4A0B 胜利，一切正确";
    	}else {
    		countB = countB-countA;
    		return countA+"A"+countB+"B";
    	}
    }
    
    
}
